-- Insert the 10 safari packages into trips table
INSERT INTO public.trips (
  title, 
  description, 
  short_description,
  image_url, 
  duration, 
  group_size, 
  price, 
  original_price, 
  rating, 
  reviews, 
  badge, 
  features, 
  destinations,
  is_featured
) VALUES 
(
  'Mara Explorer – Big Five Safari',
  'Explore Maasai Mara, the heart of Kenya''s wildlife. Witness the Big Five and the great wildebeest migration.',
  'Explore Maasai Mara, the heart of Kenya''s wildlife. Witness the Big Five and the great wildebeest migration.',
  'https://images.unsplash.com/photo-1472396961693-142e6e269027',
  '4 Days',
  'Up to 8 guests',
  890,
  990,
  4.8,
  156,
  'Popular',
  ARRAY['Game drives', 'Full-board camps', 'Park fees', 'Professional guide'],
  ARRAY['Mara'],
  true
),
(
  'Amboseli Panorama & Kilimanjaro Views',
  'A short scenic tour of Amboseli with unforgettable views of Mt. Kilimanjaro, and large elephant herds.',
  'A short scenic tour of Amboseli with unforgettable views of Mt. Kilimanjaro, and large elephant herds.',
  'https://images.unsplash.com/photo-1466721591366-2d5fba72006d',
  '3 Days',
  'Up to 6 guests',
  750,
  850,
  4.7,
  98,
  'Scenic',
  ARRAY['Park entrance', 'Game drives', 'Meals', 'Transfers'],
  ARRAY['Amboseli'],
  false
),
(
  'Nairobi Express Safari',
  'A quick urban wildlife escape including Nairobi National Park, Giraffe Centre, and Karen Blixen Museum.',
  'A quick urban wildlife escape including Nairobi National Park, Giraffe Centre, and Karen Blixen Museum.',
  'https://images.unsplash.com/photo-1518877593221-1f28583780b4',
  '2 Days',
  'Up to 10 guests',
  290,
  350,
  4.5,
  203,
  'Express',
  ARRAY['Entrance fees', 'Guide', 'Transport', 'City tour'],
  ARRAY['Nairobi'],
  false
),
(
  'Mombasa Rendezvous – Coastal Luxury Safari',
  'A coastal blend of safari and beach – Tsavo East & West, ending in white sand relaxation at Diani or Nyali.',
  'A coastal blend of safari and beach – Tsavo East & West, ending in white sand relaxation at Diani or Nyali.',
  'https://images.unsplash.com/photo-1500375592092-40eb2168fd21',
  '5 Days',
  'Up to 8 guests',
  1100,
  1250,
  4.9,
  127,
  'Luxury',
  ARRAY['Accommodation', 'Meals', 'Safari van', 'Beach resort'],
  ARRAY['Mombasa'],
  true
),
(
  'Nakuru & Lake Naivasha Flamingo Trail',
  'Discover pink flamingos in Lake Nakuru and hippo spotting in Lake Naivasha. Great for bird lovers and families.',
  'Discover pink flamingos in Lake Nakuru and hippo spotting in Lake Naivasha. Great for bird lovers and families.',
  'https://images.unsplash.com/photo-1469041797191-50ace28483c3',
  '3 Days',
  'Up to 12 guests',
  620,
  720,
  4.6,
  145,
  'Family Friendly',
  ARRAY['Boat ride', 'Park fees', 'Full board', 'Bird watching'],
  ARRAY['Nakuru'],
  false
),
(
  'Northern Circuit Discovery (Samburu – Shaba – Meru)',
  'Rugged adventure through Samburu, Buffalo Springs & Meru, home to unique wildlife like the Grevy''s zebra.',
  'Rugged adventure through Samburu, Buffalo Springs & Meru, home to unique wildlife like the Grevy''s zebra.',
  'https://images.unsplash.com/photo-1452378174528-3090a4bba7b2',
  '6 Days',
  'Up to 8 guests',
  1450,
  1650,
  4.8,
  89,
  'Adventure',
  ARRAY['Park fees', 'Camping/lodge', 'Transport', 'Wildlife tracking'],
  ARRAY['Northern Circuit'],
  false
),
(
  'Southern Circuit Retreat (Tsavo – Taita – Amboseli)',
  'A diverse southern route through dry savannahs, saltlicks and Kilimanjaro backdrops.',
  'A diverse southern route through dry savannahs, saltlicks and Kilimanjaro backdrops.',
  'https://images.unsplash.com/photo-1487252665478-49b61b47f302',
  '5 Days',
  'Up to 10 guests',
  1200,
  1400,
  4.7,
  112,
  'Diverse',
  ARRAY['Lodges', 'Game drives', 'Meals', 'Scenic views'],
  ARRAY['Southern Circuit'],
  false
),
(
  'Best of Kenya – Countrywide Safari Circuit',
  'From Maasai Mara to Samburu, Lake Nakuru to Amboseli. The complete safari loop in one unforgettable journey.',
  'From Maasai Mara to Samburu, Lake Nakuru to Amboseli. The complete safari loop in one unforgettable journey.',
  'https://images.unsplash.com/photo-1426604966848-d7adac402bff',
  '10 Days',
  'Up to 12 guests',
  2400,
  2800,
  4.9,
  234,
  'Best Value',
  ARRAY['National parks access', 'All transfers', '4x4 land cruiser', 'Full itinerary'],
  ARRAY['Kenyan Circuit'],
  true
),
(
  'East Africa Explorer – Kenya & Tanzania Combo',
  'Cross-border safari from Maasai Mara to Serengeti, Ngorongoro, Lake Manyara and Tarangire.',
  'Cross-border safari from Maasai Mara to Serengeti, Ngorongoro, Lake Manyara and Tarangire.',
  'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843',
  '12 Days',
  'Up to 8 guests',
  3600,
  4200,
  5.0,
  167,
  'Premium',
  ARRAY['Visa assistance', 'Game drives', 'Accommodation', 'Cross-border transport'],
  ARRAY['Kenya/Tanzania Circuit'],
  true
),
(
  'Tsavo Wilderness & Red Elephants Safari',
  'Discover Tsavo''s red-dusted elephants, rugged terrain and the lush Mzima Springs in Tsavo West.',
  'Discover Tsavo''s red-dusted elephants, rugged terrain and the lush Mzima Springs in Tsavo West.',
  'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
  '4 Days',
  'Up to 10 guests',
  870,
  970,
  4.8,
  134,
  'Wildlife',
  ARRAY['Park fees', 'Lodge', 'Guide', 'Meals'],
  ARRAY['Tsavo'],
  false
);